Admin.create(email: '1@1', password: '111111')
Tag.create(name: 'デブ猫')
Category.create(name:'猫')
Category.create(name:'犬')
Category.create(name:'鳥')
Category.create(name:'馬')
Category.create(name:'兎')
Category.create(name:'蛇')
Category.create(name:'熊')
Category.create(name:'魚')